[package]

name = "protobuf"
version = "2.27.1"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/stepancheg/rust-protobuf/"
repository = "https://github.com/stepancheg/rust-protobuf/"
documentation = "https://github.com/stepancheg/rust-protobuf/blob/master/README.md"
description = """
Rust implementation of Google protocol buffers
"""

[lib]
doctest = false
bench = false

[features]
with-bytes = ["bytes"]
with-serde = ["serde", "serde_derive"]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[dependencies]
bytes = { version = "1.0", default-features = false, optional = true }
serde        = { version = "1.0", optional = true, git = "https://github.com/mesalock-linux/serde-sgx", features = ["derive"] }
serde_derive = { version = "1.0", optional = true, git = "https://github.com/mesalock-linux/serde-sgx" }
sgx_tstd = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk.git", optional = true }

[package.metadata.docs.rs]
all-features = true
